### PR TITLE
Add option to dismiss banner on click (anywhere on the page)

### PR DESCRIPTION
**Pull request by camilledalmeras**
The accept-on-scroll feature is lovely, this one might complement it usefully.

### CODE REVIEW

**Comment by senko** [comment]
Looks good to me. @zytzagoo want to chime in?

Btw as I'm pretty much inactive on the project, @zytzagoo would you be interested in taking over the maintenance of the project?

**Comment by zytzagoo** [comment]
@senko having some tests covering the new option would be great, but since there were other options/features already merged without tests I guess it's not a blocker.

re: maintenance, sure, I'll help out while I can (my 5mo son might make it hard to always find the time) :)

**Comment by senko** [comment]
Sounds good :)

**Comment by senko** [comment]
@camilledalmeras thanks for the patch!

**Comment by camilledalmeras** [comment]
@senko You're very much welcome, I am the one who is grateful for all your and others' good work on cookie-banner

@zytzagoo re: 5mo babies: that sounds all too familiar... Stay strong! ;)

**Pull request merged**
